### ISSUE TITLE
VisualEfectGraph使ってみたいのですが、いかかでござるか？

### ISSUE THREAD

**Issue by koiusa** [work-room-umi/ld50-sandbox#24]
がっつり使ってる方いたりするんでしょうか？

**Comment by HarukaKajita** [comment]
僕は全然使ってないけど、使ってるとしたらのりべんさんかな。 @noriben327 
LTSのUnity使うし、対応プラットフォームもPCだしVFX Graphありな気がしますね！

**Comment by noriben327** [comment]
VFX Graphはちょっと触ったくらいですね。ありだとは思います。
